config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root to: 'events#index'

	resources :users
	resources :events
	resources :attendances

	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event
  belongs_to :user
    after_create :eventmail_send

  def eventmail_send
    EventmailerMailer.eventmail(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user
	has_many :attendances 
	has_many :users, through: :attendances
	validate :expiration_date_cannot_be_in_the_past
	validate :modulo_duration
	validates :title,presence: true,length: { minimum: 5, maximum: 140 }
	validates :description,presence: true,length: { minimum: 20, maximum: 1000 }
	validates :price,presence: true,numericality: { only_integer: true, greater_than: 1 , less_than_or_equal_to: 1000 }
	validates :location,presence: true 
  def expiration_date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    end
  end
     def modulo_duration
    if duration.present? && duration % 5 !=0 && duration >= 0
      errors.add(:start_date, "can't be in the past")
    end
  end
  def modulo_price
    if duration.present? && duration % 5 !=0 && duration >= 0
      errors.add(:start_date, "can't be in the past")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	after_create :welcome_send
	has_many :events
	has_many :attendances
	has_many :events ,through: :attendances
	 def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
	end

	def new
		@event = Event.new
	end

	def create 
		@event = Event.new(start_date: params[:start_date], duration: params[:duration],title: params[:title], description: params[:description], price: params[:price], location: params[:location], user: current_user)
		if @event.errors.any?
			render :new
		end
		if @event.save
			redirect_to root_path
		else 
			render :new
		end
	end

	def show 
		@event = Event.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user! 
	def show
		@user = User.find(params[:id])
		@event = @user.events
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<header id="head">
    <div class="container">
      <h2 class="display-5">Welcome on EventBrite!</h2>
        <!-- <i class="fas fa-heart"></i> -->
      </div>
  </header>
  <!-- /Header -->

      <!-- Main jumbotron for a primary marketing message or call to action -->
    
   <%  @events = Event.all %>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <% @events.each do |event| %>
          <div class="col-md-4">
            <h2><%= event.title %></h2>
            <p><%= event.description %></p>
            <p><a class="btn btn-secondary" href="<%= event_path(event.id) %>" role="button">En savoir plus &raquo;</a></p>
          </div>
          <% end %>
        </div>

app/views/events/new.html.erb
<div class="card border-info m-5">
 <div class="card-header">
  <h1>Create your own event!</h1>
</div>
<%= form_tag url_for(action: 'create'), method: "post" do %>
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

<div class="card-body text-info">
  <div class="form-group">
    <%= text_field_tag 'title', @event.title, class: "form-control", placeholder: "Name of your event" %>
    <%= text_area_tag 'start_date', @event.start_date, class: "form-control", placeholder: "Start date" %>
    <%= date_field(:event, :start_date) %>
    <%= text_area_tag 'duration', @event.duration, class: "form-control", placeholder: "Duration" %>
    <%= text_field_tag 'location', @event.location, class: "form-control", placeholder: "The place to be" %>
    <%= text_area_tag 'description', @event.description, class: "form-control", placeholder: "Description" %>
    <%= text_field_tag 'price', @event.price, class: "form-control", placeholder: "Price" %>
    <br /> <br />

    <%= submit_tag "Add my event", class: "btn btn-info" %>
    <% end %>
  </div>
</div>
</div>
<% if @event.errors.any? %>
<div class="alert alert-danger" role="alert">
  <p>We were unable to create your event for the following reasons:</p>
  <ul>
    <% @event.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/events/show.html.erb
<div>
	<%= @event.title %> <br>
	Date : <%= @event.start_date %> <br>
	Durée : <%= @event.duration %> <br>
	Lieu <%= @event.location %> <br>
	Description : <%= @event.description %> <br>
	Tarif : <%= @event.price %> <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventbriteThp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">EventBrite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to "Create an event", new_event_path, :class => "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          My Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Profil", current_user, :class => "dropdown-item" %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sign in / Sign up
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Sign up", new_user_session_path, :class => "dropdown-item" %>
          <%= link_to "Sign in", new_user_registration_path, :class => "dropdown-item" %>
        </div>
      </li>
      <% end %>

    </ul>
  </div>
</nav>



  <%= yield %>
</body>
</html>

app/views/users/show.html.erb
<div class="container">
	<div class="row text-center justify-content-center mt-3">
		
		<h1 class="col-12"><%="#{@user.first_name}" %> <%="#{@user.last_name}"%></h1>

	

		<p class="col-12">
			<h3>Description</h3><br/>
			<%= @user.description %>
		</p>
		
		<p class="col-12">
			<small class="text-muted">Email</small><br/>
			<%= @user.email %>
		</p>
			<%= link_to "Edit profile", edit_user_registration_path, class: 'btn btn-primary' %>
	</div>

	
	<div class="row">	
		<% @event.each do |event| %>
		<div class="card col-12 mb-3">
			<div class="card-body">
				<h5 class="card-title"><%= event.title %></h5>
				<h6 class="card-subtitle mb-2 text-muted"><%= event.location %></h6>
				<p class="card-text"><%= event.price %> €</p>
				<%= link_to "See more",  event_path(event.id), class:"btn-primary btn-sm" %>
			</div>
		</div>
		<% end %>
	</div>
</div>
</div>